# Generated by Django 2.2 on 2019-05-22 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
